[build-system]
requires = [
    "setuptools >= 67",
    "wheel >= 0.38",
]
build-backend = "setuptools.build_meta"

[tool.back]
line-length = 99

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
